OUT_DIR := "./out"
THIRD_PARTY_DIR := "./third-party"

[parallel]
default: (stl "12v_psu_din_mount") \
         (stl "48v_psu_din_mount/bracket") \
         (dxf "48v_psu_din_mount/cap") \
         (dxf "control_cabinet_panel/panel") \
         (dxf "control_cabinet_panel/panel_corner_insert") \
         (dxf "control_cabinet_panel/panel_recesses") \
         (dxf "control_cabinet_panel/shield_bottom") \
         (stl "control_cabinet_panel/shield_bracket_panel") \
         (stl "control_cabinet_panel/shield_bracket_rail") \
         (dxf "control_cabinet_panel/shield_top") \
         (stl "picocnc_din_mount") \
         (stl "stepper_driver_din_mount")

dependencies:
    mkdir -p "{{THIRD_PARTY_DIR}}"

    if [ ! -d "{{THIRD_PARTY_DIR}}/SCAD_Lib" ]; then \
        git clone "https://github.com/DanNixon/SCAD_Lib" "{{THIRD_PARTY_DIR}}/SCAD_Lib"; \
        git -C "{{THIRD_PARTY_DIR}}/SCAD_Lib" checkout "5f1376045233f56996e4676769979bd5ab3ea55c"; \
    fi

dxf FILE: dependencies
    mkdir -p $(dirname {{OUT_DIR}}/{{FILE}}.dxf)
    openscad -o {{OUT_DIR}}/{{FILE}}.dxf {{FILE}}.scad

stl FILE: dependencies
    mkdir -p $(dirname {{OUT_DIR}}/{{FILE}}.dxf)
    openscad -o {{OUT_DIR}}/{{FILE}}.stl {{FILE}}.scad

clean:
    rm -rf {{OUT_DIR}}
    rm -rf {{THIRD_PARTY_DIR}}
